### ISSUE TITLE
failed in simple requesting emails

### ISSUE THREAD

**Issue by codeorbit** [prodicus/plino#22]
it failed when you write a mail requesting for someone's help. May be it is because of algorithm.
![plino](https://cloud.githubusercontent.com/assets/13711394/14504612/24590c5a-01d3-11e6-88ea-235d0a0dcea0.png)

**Comment by prodicus** [comment]
Hey @codeorbit . Thanks for trying our service out.

We never did promise 100% accuracy on our classifier. As always there are always gonna be some false positives. Hope this answers your question :smile:

**Comment by codeorbit** [comment]
But you did mentioned "An intelligent spam filetering" :confused:

**Comment by sinscary** [comment]
@codeorbit  Actually it was spam, because we din't sent any such email. :laughing:

**Comment by codeorbit** [comment]
@sinscary @prodicus  its a requesting email asking for help!!  :stuck_out_tongue_closed_eyes:

**Comment by prodicus** [comment]
@codeorbit Well, Plino stands open sourced. 

Feel free to make a PR to make it better :grin: .
