### ISSUE TITLE
Show a loader when user clicks on "Classify"

### ISSUE THREAD

**Issue by sahildua2305** [prodicus/plino#23]
If I enter a text that's not a spam, it shows the corresponding result in a green badge. Now if I enter another text that's not a spam again, it will keep showing the same text and I won't get to know whether that text is actually a ham or did it not send any response to my new request.

There should be a loader as soon as request is sent and then once the response is received, then the badge with ham/spam text should be displayed. This way people with slow internet will have a good experience and those with a fast one will get to know how fast does this actually work. :)

I will add the loader in sometime if you think it's a good idea. @prodicus

**Comment by prodicus** [comment]
Good catch @sahildua2305 :+1:

**Comment by sahildua2305** [comment]
@prodicus I can't see changes on the heroku app. Haven't you pushed the changes there?

**Comment by prodicus** [comment]
Sorry for the delay. Pushed it to heroku. You can cross @sahildua2305 and verify for the same :smile:

**Comment by sahildua2305** [comment]
Good now :+1:
