### ISSUE TITLE
CLI ?

### ISSUE THREAD

**Issue by rborn** [prodicus/plino#27]
Hey, would be amazing if a CLI could be created for this tool to feed a procmail file for spam processing :)

**Comment by sinscary** [comment]
@rborn  that's a great idea. :+1:

**Comment by rborn** [comment]
Also the possibility to train it using the _Maildir_ format? 😊 
Sadly I don't know python but I could help with the tests 😄 

Thanks!

**Comment by sinscary** [comment]
Well @prodicus  take it up than.

**Comment by prodicus** [comment]
@rborn You can have a look at [spammy](https://github.com/prodicus/spammy) for that matter. You can easily build a CLI app using it. 

Coming to the maildir format. The training process is designed such that it gets trained by reading data from mails in a format like

```
├── ham
│   ├── 5458.2001-04-25.kaminski.ham.txt
│   ├── 5459.2001-04-25.kaminski.ham.txt
│   ...
│   ...
│   └── 5851.2001-05-22.kaminski.ham.txt
└── spam
    ├── 4136.2005-07-05.SA_and_HP.spam.txt
    ├── 4137.2005-07-05.SA_and_HP.spam.txt
    ...
    ...
    └── 5269.2005-07-19.SA_and_HP.spam.txt
```

Hope it helps @rborn

**Comment by rborn** [comment]
I'll give it a try, thank you.

**Comment by prodicus** [comment]
@rborn Closing this issue then
